/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DilshanRajika
 */
public class Paymentform extends javax.swing.JFrame {

    /**
     * Creates new form Paymentform
     */
    public Paymentform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datetext = new javax.swing.JTextField();
        cvvtext = new javax.swing.JPasswordField();
        holdername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numbertext = new javax.swing.JTextField();
        checketout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 304, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 590, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled-1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 420, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CVV");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 40, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card Holder Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expration Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        datetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetextActionPerformed(evt);
            }
        });
        jPanel1.add(datetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));

        cvvtext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cvvtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvtextActionPerformed(evt);
            }
        });
        jPanel1.add(cvvtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 70, -1));

        holdername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        holdername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdernameActionPerformed(evt);
            }
        });
        jPanel1.add(holdername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Card Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        numbertext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numbertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbertextActionPerformed(evt);
            }
        });
        jPanel1.add(numbertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 220, -1));

        checketout.setBackground(new java.awt.Color(0, 153, 51));
        checketout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checketout.setText("PayNow");
        checketout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checketoutActionPerformed(evt);
            }
        });
        jPanel1.add(checketout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 310, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer-service_payment-options-tile.jpg"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetextActionPerformed

    private void holdernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holdernameActionPerformed

    private void cvvtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvtextActionPerformed

    private void numbertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbertextActionPerformed

    private void checketoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checketoutActionPerformed
      
        if(holdername.getText().length()>0&&numbertext.getText().length()==16&&cvvtext.getText().length()==3&&datetext.getText().length()==8){
         String vehicleid=ReseptionFormViewer.Searchid.getText();
        String vehicletype=ReseptionFormViewer.Vehicletypebox.getSelectedItem().toString();
        String custname=ReseptionFormViewer.customername.getText();
        String intime=ReseptionFormViewer.intimetext.getText();
        String outtime=ReseptionFormViewer.outtimetext.getText();
        double payment=Double.parseDouble(ReseptionFormViewer.paymenttxt.getText());
        Vehicle vehicle=new Vehicle(vehicleid,vehicletype,custname,intime,outtime,payment);
            JOptionPane.showMessageDialog(null,"Payment Successfully"); 
            try {
                boolean payed=VehicleController.Updatecustomer(vehicle);
            } catch (ClassNotFoundException | SQLException ex) {
                     String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
            }
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Tryagain!");
             this.dispose();
        }
       
    }//GEN-LAST:event_checketoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paymentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paymentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paymentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paymentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paymentform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checketout;
    private javax.swing.JPasswordField cvvtext;
    private javax.swing.JTextField datetext;
    private javax.swing.JTextField holdername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField numbertext;
    // End of variables declaration//GEN-END:variables
}
