/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author DilshanRajika
 */
public class ReseptionFormViewer extends javax.swing.JFrame {

    /**
     * Creates new form ReseptionFormViewer
     */
    public ReseptionFormViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ViewParkingButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Searchid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        intimetext = new javax.swing.JTextField();
        outtimetext = new javax.swing.JTextField();
        paymenttxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Vehicletypebox = new javax.swing.JComboBox<>();
        CaluulatetimeButton = new javax.swing.JButton();
        Updatebutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cancelButton1 = new javax.swing.JButton();
        CostClculate = new javax.swing.JButton();
        VehicleparkInfButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C2020 Microsoft Corporation.All rights reseived");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        ViewParkingButton.setBackground(new java.awt.Color(204, 255, 204));
        ViewParkingButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewParkingButton.setText("ViewParking");
        ViewParkingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewParkingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewParkingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewParkingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 640, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("      Welcome Sunrise Shopping Complex");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 550, 60));

        Searchid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Searchid.setForeground(new java.awt.Color(0, 0, 204));
        Searchid.setBorder(null);
        Searchid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Searchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchidActionPerformed(evt);
            }
        });
        jPanel1.add(Searchid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 270, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" VehicleID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));

        customername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customername.setForeground(new java.awt.Color(0, 0, 204));
        customername.setBorder(null);
        customername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        customername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customernameActionPerformed(evt);
            }
        });
        jPanel1.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 370, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CustomerName");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Arraival Time");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        intimetext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        intimetext.setForeground(new java.awt.Color(0, 0, 204));
        intimetext.setBorder(null);
        intimetext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        intimetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intimetextActionPerformed(evt);
            }
        });
        jPanel1.add(intimetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 370, 30));

        outtimetext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outtimetext.setForeground(new java.awt.Color(0, 0, 204));
        outtimetext.setBorder(null);
        outtimetext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        outtimetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outtimetextActionPerformed(evt);
            }
        });
        jPanel1.add(outtimetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 370, 30));

        paymenttxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymenttxt.setForeground(new java.awt.Color(0, 0, 204));
        paymenttxt.setBorder(null);
        paymenttxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        paymenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttxtActionPerformed(evt);
            }
        });
        jPanel1.add(paymenttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Departure Time");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VehicleType");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 130, 30));

        Vehicletypebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Vehicletypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bus", "Van", "Lorry" }));
        Vehicletypebox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vehicletypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicletypeboxActionPerformed(evt);
            }
        });
        jPanel1.add(Vehicletypebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, 30));

        CaluulatetimeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CaluulatetimeButton.setText("Card Pyment ");
        CaluulatetimeButton.setBorder(null);
        CaluulatetimeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CaluulatetimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaluulatetimeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CaluulatetimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 100, 30));

        Updatebutton.setBackground(new java.awt.Color(204, 255, 204));
        Updatebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Updatebutton.setText("Save");
        Updatebutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Updatebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cash/ Payment");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));

        cancelButton1.setBackground(new java.awt.Color(204, 255, 204));
        cancelButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelButton1.setText("Cancel");
        cancelButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, 30));

        CostClculate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CostClculate.setText("CalculateCost");
        CostClculate.setActionCommand("CalculateCost");
        CostClculate.setBorder(null);
        CostClculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CostClculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostClculateActionPerformed(evt);
            }
        });
        jPanel1.add(CostClculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, 30));

        VehicleparkInfButton.setBackground(new java.awt.Color(204, 255, 204));
        VehicleparkInfButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehicleparkInfButton.setText("Parking Inf");
        VehicleparkInfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VehicleparkInfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleparkInfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VehicleparkInfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rescptionwallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 650, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchidActionPerformed
          String id=Searchid.getText();
        
        try {
            Vehicle vehicle=VehicleController.SearchVehicle(id);
            if(vehicle !=null){
            Searchid.setText(vehicle.getVehicleID());
            Vehicletypebox.setSelectedItem(vehicle.getVehicleType());
            customername.setText(vehicle.getCustomerName());
            intimetext.setText(vehicle.getIntime());
            outtimetext.setText(vehicle.getOuttime());
            paymenttxt.setText(Double.toString(vehicle.getPayments()));
           
            }else{
             JOptionPane.showMessageDialog(null,"Vehicle Not Found","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
                String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SearchidActionPerformed

    private void customernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customernameActionPerformed

    private void intimetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intimetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intimetextActionPerformed

    private void outtimetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outtimetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outtimetextActionPerformed

    private void paymenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttxtActionPerformed

    private void VehicletypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicletypeboxActionPerformed

    }//GEN-LAST:event_VehicletypeboxActionPerformed

    private void CaluulatetimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaluulatetimeButtonActionPerformed
       new Paymentform().setVisible(true);
    }//GEN-LAST:event_CaluulatetimeButtonActionPerformed

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
       if(Searchid.getText().length()>0){ 
        String vehicleid=Searchid.getText();
        String vehicletype=Vehicletypebox.getSelectedItem().toString();
        String custname=customername.getText();
        String intime=intimetext.getText();
        String outtime=outtimetext.getText();
        double payment=Double.parseDouble(paymenttxt.getText());
        Vehicle vehicle=new Vehicle(vehicleid,vehicletype,custname,intime,outtime,payment);
        try {
            boolean update=VehicleController.Updatecustomer(vehicle);
            if(update){
              JOptionPane.showMessageDialog(null,"Save Successfully!");
            }else{
             JOptionPane.showMessageDialog(null,"Save Fail!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
              String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
       }else{
          JOptionPane.showMessageDialog(null,"Enter VehicleID","",JOptionPane.WARNING_MESSAGE);
       }
    
    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void ViewParkingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewParkingButtonActionPerformed
        try {
            new ViewParking().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
                    String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewParkingButtonActionPerformed

    private void CostClculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostClculateActionPerformed
       String intime=intimetext.getText();
       String outtime=outtimetext.getText();
       String vehicletype=Vehicletypebox.getSelectedItem().toString();
        try {
            double value=VehicleController.CalculateCost(intime,outtime,vehicletype);
            if(value>0){
             paymenttxt.setText(Double.toString(value));
            }else{
            JOptionPane.showMessageDialog(null,"Cost Calculate is Fail","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (ParseException ex) {
                String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CostClculateActionPerformed

    private void VehicleparkInfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleparkInfButtonActionPerformed
        try {
            new ParkingInf().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
                  String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VehicleparkInfButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReseptionFormViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReseptionFormViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReseptionFormViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReseptionFormViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReseptionFormViewer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaluulatetimeButton;
    private javax.swing.JButton CostClculate;
    public static javax.swing.JTextField Searchid;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JButton VehicleparkInfButton;
    public static javax.swing.JComboBox<String> Vehicletypebox;
    private javax.swing.JButton ViewParkingButton;
    private javax.swing.JButton cancelButton1;
    public static javax.swing.JTextField customername;
    public static javax.swing.JTextField intimetext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField outtimetext;
    public static javax.swing.JTextField paymenttxt;
    // End of variables declaration//GEN-END:variables
}
