/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DilshanRajika
 */
public class VehiclearraivalForm extends javax.swing.JFrame {

    /**
     * Creates new form VehicleMainForm
     */
    public VehiclearraivalForm() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vehicleidtext = new javax.swing.JTextField();
        customernametext = new javax.swing.JTextField();
        intimetext = new javax.swing.JTextField();
        vehicletypebox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        Registerbutton = new javax.swing.JButton();
        lorry = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        van = new javax.swing.JLabel();
        bus = new javax.swing.JLabel();
        VehicleparkInfButton = new javax.swing.JButton();
        datetext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Arraival Form ");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(620, 340));
        jLabel1.setMinimumSize(new java.awt.Dimension(620, 340));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 280, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 620, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" VehicleID");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VehicleType");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CustomerName");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Arraival Time");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        vehicleidtext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehicleidtext.setForeground(new java.awt.Color(0, 0, 204));
        vehicleidtext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        vehicleidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleidtextActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 270, 30));

        customernametext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customernametext.setForeground(new java.awt.Color(0, 0, 204));
        customernametext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        customernametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customernametextActionPerformed(evt);
            }
        });
        jPanel1.add(customernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 370, 30));

        intimetext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        intimetext.setForeground(new java.awt.Color(0, 0, 204));
        intimetext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        intimetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intimetextActionPerformed(evt);
            }
        });
        jPanel1.add(intimetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 370, 30));

        vehicletypebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vehicletypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bus", "Van", "Lorry" }));
        vehicletypebox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehicletypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletypeboxActionPerformed(evt);
            }
        });
        jPanel1.add(vehicletypebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, 30));

        cancelButton.setBackground(new java.awt.Color(204, 255, 204));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 100, 30));

        Registerbutton.setBackground(new java.awt.Color(204, 255, 204));
        Registerbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Registerbutton.setText("Register");
        Registerbutton.setBorder(null);
        Registerbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, 30));

        lorry.setBackground(new java.awt.Color(102, 51, 255));
        lorry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lorry.setForeground(new java.awt.Color(255, 255, 255));
        lorry.setText("10/10 Lorry Slots");
        lorry.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lorry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lorry, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 30));

        car.setBackground(new java.awt.Color(102, 51, 255));
        car.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        car.setForeground(new java.awt.Color(255, 255, 255));
        car.setText("40/ 40 Car Slots");
        car.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        car.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(car, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        van.setBackground(new java.awt.Color(102, 51, 255));
        van.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        van.setForeground(new java.awt.Color(255, 255, 255));
        van.setText("30/ 30 Van  Slots");
        van.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        van.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(van, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 30));

        bus.setBackground(new java.awt.Color(102, 51, 255));
        bus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bus.setForeground(new java.awt.Color(255, 255, 255));
        bus.setText("20/ 20 Bus Slots");
        bus.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 130, 30));

        VehicleparkInfButton.setBackground(new java.awt.Color(204, 255, 204));
        VehicleparkInfButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VehicleparkInfButton.setText("Parking Inf");
        VehicleparkInfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VehicleparkInfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleparkInfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VehicleparkInfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, 30));

        datetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(datetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lexus-red.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleidtextActionPerformed

    private void customernametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customernametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customernametextActionPerformed

    private void intimetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intimetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intimetextActionPerformed

    private void vehicletypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletypeboxActionPerformed
                
    }//GEN-LAST:event_vehicletypeboxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void RegisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbuttonActionPerformed
    
        if(vehicleidtext.getText().length()>0&&customernametext.getText().length()>0&&datetext.getText().length()==10){
         String  vehicleid=vehicleidtext.getText();
         String vehicletype=vehicletypebox.getSelectedItem().toString();
         String customername=customernametext.getText();
         String intime=intimetext.getText();
         String date=datetext.getText();
        try {
             Vehicle vehicle=new Vehicle(vehicleid,vehicletype,customername,intime,date);
            boolean registered =VehicleController.RegisterVahicle(vehicle,vehicletype);
            if(registered){
           
                JOptionPane.showMessageDialog(null,"Vehicle Registered Successfully");
                vehicleidtext.setText(null);
                customernametext.setText(null);
                intimetext.setText(null);
                vehicleidtext.setText(null);
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
                String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
        }else{
            if(datetext.getText().length()!=10){
           JOptionPane.showMessageDialog(null,"Invalid Date!","",JOptionPane.WARNING_MESSAGE);
            }else{
             JOptionPane.showMessageDialog(null,"Some fields are Empty!","",JOptionPane.WARNING_MESSAGE);
            }
          
        }
    }//GEN-LAST:event_RegisterbuttonActionPerformed

    private void VehicleparkInfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleparkInfButtonActionPerformed
        try {
            new ParkingInf().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VehicleparkInfButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiclearraivalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VehiclearraivalForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registerbutton;
    private javax.swing.JButton VehicleparkInfButton;
    public static javax.swing.JLabel bus;
    private javax.swing.JButton cancelButton;
    public static javax.swing.JLabel car;
    private javax.swing.JTextField customernametext;
    private javax.swing.JTextField datetext;
    private javax.swing.JTextField intimetext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lorry;
    public static javax.swing.JLabel van;
    private javax.swing.JTextField vehicleidtext;
    public javax.swing.JComboBox<String> vehicletypebox;
    // End of variables declaration//GEN-END:variables
}
