/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DilshanRajika
 */
public class VehicleDepartureForm extends javax.swing.JFrame {
    /**
     * Creates new form VehicleMainForm
     */
    public VehicleDepartureForm() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Searchid = new javax.swing.JTextField();
        customername = new javax.swing.JTextField();
        intime = new javax.swing.JTextField();
        paymenttxt = new javax.swing.JTextField();
        Vehicletypebox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        CheckButton = new javax.swing.JButton();
        outtime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datetext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Departure Form ");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(620, 340));
        jLabel1.setMinimumSize(new java.awt.Dimension(620, 340));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 620, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VehicleType");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CustomerName");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));

        Searchid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Searchid.setForeground(new java.awt.Color(0, 0, 204));
        Searchid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Searchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchidActionPerformed(evt);
            }
        });
        jPanel1.add(Searchid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 270, 30));

        customername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customername.setForeground(new java.awt.Color(0, 0, 204));
        customername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        customername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customernameActionPerformed(evt);
            }
        });
        jPanel1.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 370, 30));

        intime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        intime.setForeground(new java.awt.Color(0, 0, 204));
        intime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        intime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intimeActionPerformed(evt);
            }
        });
        jPanel1.add(intime, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 370, 30));

        paymenttxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymenttxt.setForeground(new java.awt.Color(0, 0, 204));
        paymenttxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        paymenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttxtActionPerformed(evt);
            }
        });
        jPanel1.add(paymenttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 370, 30));

        Vehicletypebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Vehicletypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bus", "Van", "Lorry" }));
        Vehicletypebox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vehicletypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicletypeboxActionPerformed(evt);
            }
        });
        jPanel1.add(Vehicletypebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, 30));

        cancelButton.setBackground(new java.awt.Color(204, 255, 204));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 100, 30));

        CheckButton.setBackground(new java.awt.Color(204, 255, 204));
        CheckButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckButton.setText("Check");
        CheckButton.setBorder(null);
        CheckButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 100, 30));

        outtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outtime.setForeground(new java.awt.Color(0, 0, 204));
        outtime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        outtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outtimeActionPerformed(evt);
            }
        });
        jPanel1.add(outtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 370, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Arraival Time");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Departure Time");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        datetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datetext.setBorder(null);
        jPanel1.add(datetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" VehicleID");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lexus-red.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchidActionPerformed
            
    }//GEN-LAST:event_SearchidActionPerformed

    private void customernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customernameActionPerformed

    private void intimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intimeActionPerformed

    private void paymenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttxtActionPerformed

    private void VehicletypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicletypeboxActionPerformed
                
    }//GEN-LAST:event_VehicletypeboxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        String id=Searchid.getText();
        
        try {
            Vehicle vehicle=VehicleController.SearchVehicle(id);
            if(vehicle !=null){
            Searchid.setText(vehicle.getVehicleID());
            Vehicletypebox.setSelectedItem(vehicle.getVehicleType());
            customername.setText(vehicle.getCustomerName());
            intime.setText(vehicle.getIntime());
            outtime.setText(vehicle.getOuttime());
            datetext.setText(vehicle.getDate());
            paymenttxt.setText(Double.toString(vehicle.getPayments()));
            }else{
             JOptionPane.showMessageDialog(null,"Vehicle Not Found","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
                String message=ex.getMessage();
            JOptionPane.showMessageDialog(null, message,"",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void outtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outtimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleDepartureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleDepartureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleDepartureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleDepartureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VehicleDepartureForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JTextField Searchid;
    private javax.swing.JComboBox<String> Vehicletypebox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField datetext;
    private javax.swing.JTextField intime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField outtime;
    private javax.swing.JTextField paymenttxt;
    // End of variables declaration//GEN-END:variables
}
